------------------------------------------------------------
--XDisparadores
------------------------------------------------------------

DROP TRIGGER TR_ACTUALIZAR_ESTADO_MEMBRESIA;
DROP TRIGGER TR_CALCULAR_FECHA_FIN_MEMBRESIA;
DROP TRIGGER TR_CALCULAR_IMC_USUARIOS;
DROP TRIGGER TR_INCREMENTAR_CONSEJOS_ESPECIALISTA;
DROP TRIGGER TR_BLOQUEAR_MODIFICACION_FEEDBACK;
DROP TRIGGER TR_VALIDAR_FECHA_FEEDBACK;
DROP TRIGGER TR_VALIDAR_FECHA_OBJETIVO;
DROP TRIGGER TR_VALIDAR_FECHA_PROGRESO;
