----------------------------------
-- XTablas
-- Eliminación de tablas
----------------------------------

DROP TABLE Feedbacks CASCADE CONSTRAINTS;
DROP TABLE Recomendaciones CASCADE CONSTRAINTS;
DROP TABLE Objetivos CASCADE CONSTRAINTS;
DROP TABLE Progresos CASCADE CONSTRAINTS;
DROP TABLE PlanesFitnessDeUsuarios CASCADE CONSTRAINTS;
DROP TABLE Rutinas CASCADE CONSTRAINTS;
DROP TABLE Comidas CASCADE CONSTRAINTS;
DROP TABLE Habitos CASCADE CONSTRAINTS;
DROP TABLE Ejercicios CASCADE CONSTRAINTS;
DROP TABLE ObjetivosRecomendaciones CASCADE CONSTRAINTS;
DROP TABLE RutinasDeEjemplo CASCADE CONSTRAINTS;
DROP TABLE EjerciciosDeRutinasDeEjemplo CASCADE CONSTRAINTS;
DROP TABLE PlanesFitness CASCADE CONSTRAINTS;
DROP TABLE Usuarios CASCADE CONSTRAINTS;
DROP TABLE EspecialistasFitness CASCADE CONSTRAINTS;
DROP TABLE Personas CASCADE CONSTRAINTS;